# Generated by Django 5.0.14 on 2026-07-11 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_statement_status'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama (local)'), ('deepseek', 'DeepSeek'), ('openrouter', 'OpenRouter (Claude, GPT, Gemini, Llama, ...)')], default='ollama', max_length=32)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('base_url', models.URLField(blank=True, help_text='Overrides the provider default. Leave blank for the default.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='core.organization')),
            ],
            options={
                'verbose_name': 'AI settings',
                'verbose_name_plural': 'AI settings',
            },
        ),
    ]
